name: Build and Publish

on:
  schedule:
    # At 04:00 on day-of-month 1.
    - cron: "0 4 1 * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Get Docker tags
        id: get-tags
        run: |
          IMAGE_NAME="library/alpine"
          curl -s "https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags?page_size=200" > docker_tags.json

      - uses: cloudposse/github-action-jq@main
        id: parse-tags
        with:
          compact: true
          input: docker_tags.json
          script: ".results | map(select((.name | contains(\".\")) and (.name | contains(\"-\") | not) and (.name | contains(\"_\") | not) or .name == \"latest\")) | map(.name)          "

      - name: Set matrix for build
        run: |
          echo '{"tag": ${{ steps.parse-tags.outputs.output }}}' >> config.json

      - uses: cloudposse/github-action-jq@main
        id: reparse-tags
        with:
          compact: true
          input: config.json
          script: "."

      - run: echo 'matrix=${{ steps.reparse-tags.outputs.output }}' >> $GITHUB_OUTPUT
        id: set-matrix

  build:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          logout: true

      - name: Build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            ALPINE_VERSION=${{ matrix.tag }}
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: betterweb/alpine:${{matrix.tag}}
