name: Build and Publish

on:
  push:
    branches:
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=betterweb/alpine
          VERSION=latest
          SHORTREF=${GITHUB_SHA::8}

          TAGS="${DOCKER_IMAGE}:latest"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        run: echo $DOCKER_HUB_TOKEN > ~/.docker/config.json ; echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_HUB_TOKEN\"}}}" > ~/.docker/config.json

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./src
          file: ./Dockerfile
          platforms: amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, riscv64, s390x
          push: true
          tags: ${{ steps.prep.outputs.tags }}

      - name: cleanup
        if: always()
        run: rm -rf ~/.docker ; rm -rf ~/.docker;
