name: Build and Publish

on:
  schedule:
    # At 04:00 on day-of-month 1.
    - cron: '0 4 1 * *'
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get Docker tags
        id: get-tags
        run: |
          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{IMAGE_NAME}}/tags?page_size=200" | jq -r '.results[].name')
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Set matrix for build
        id: set-matrix
        run: |
          MATRIX="{\"tag\": [${{ steps.get-tags.outputs.tags }}]}"
          echo "matrix=${MATRIX}" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          logout: true

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: betterweb/alpine:${{matrix.tag}}
