name: Build and Publish

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm32,arm64,i386,ppc64le,riscv64,s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo $DOCKER_HUB_TOKEN > ~/.docker/config.json ; echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_HUB_TOKEN\"}}}" > ~/.docker/config.json

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm32,linux/arm64,linux/i386,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          tags: betterweb/alpine:latest

      - name: cleanup
        if: always()
        run: rm -rf ~/.docker ; rm -rf ~/.docker;
